#!/bin/bash
java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     distributedcvm.DistributedCVM my-URI-oven config.xml &

java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     distributedcvm.DistributedCVM my-URI-controller config.xml &

java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     distributedcvm.DistributedCVM my-URI-fridge config.xml &

java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     distributedcvm.DistributedCVM my-URI-production config.xml &

java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     distributedcvm.DistributedCVM my-URI-counter config.xml &

java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     distributedcvm.DistributedCVM my-URI-tv config.xml &
     
java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     distributedcvm.DistributedCVM my-URI-wind config.xml &
